### ISSUE TITLE
Please invite me to the GitHub Community Organisation

### ISSUE THREAD

**Issue by sailingwithsandeep** [The-Debuggerz/support#16]
### Name

Sandeep Parmar

### Discord Username (if applicable)

Lucifer.TheDeviL#6829

### Additional Context

I came to know about this from discord.
Having 10 months of experience in backend development .
And i think i can provide my inputs 
So, yeah..............

**Comment by mujibsayyad** [comment]
Welcome to The Debuggers organisation.
