### ISSUE TITLE
Please invite me to the GitHub Community Organisation

### ISSUE THREAD

**Issue by Shreybanugariya** [The-Debuggerz/support#19]
### Name

Shrey Banugaria

### Additional Context

I came to know about The Debuggers through one of my friends. I would love to contribute to the community and work on open source projects, create new ones, and update existing and rebuilt older ones. I am a Node.js Backend developer and working with JS is my favourite work and pass time. I am here to learn more and contribute as much as I can.

**Comment by mujibsayyad** [comment]
Welcome to The Debuggers organisation.
Make sure to join discord server as well for to continue conversation on project.
