### ISSUE TITLE
Please invite me to the GitHub Community Organisation

### ISSUE THREAD

**Issue by PrayagTalaviya** [The-Debuggerz/support#24]
### Name

prayag talalviya

### Discord Username (if applicable)

prayag_talaviya#8729

### Additional Context

Hello I am full-stack developer in Angular and nodeJs

**Comment by mujibsayyad** [comment]
Welcome To The Debuggers organisation.
Make sure to join discord server as well for conversation

**Comment by PrayagTalaviya** [comment]
yes I already join
