### ISSUE TITLE
Please invite me to the GitHub Community Organisation

### ISSUE THREAD

**Issue by zeelmodi-simform** [The-Debuggerz/support#27]
### Name

Zeel Modi

### Additional Context

Just came to know about when scrolling through feed

**Comment by mujibsayyad** [comment]
Hi, I have sent you invitation through mail.

Please follow mandotory steps after joining from [README.md](https://github.com/The-Debuggerz#mandatory-steps-after-joining)
If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, 
you should join our [Discord Server](https://discord.gg/metueyBQ9f)
we help and encourage each other to contribute to open source little and often!
